#!/bin/sh

. ./ci-vars.sh
. ./scripts/common-functions.sh

ROOT=$(pwd)
BUILD_DIR=${ROOT}/build
echo "${0}: BUILD_DIR - ${BUILD_DIR}"
CMAKE_DEFAULT_ARGS=$(get_cmake_default_args ${BUILD_DIR})
CMAKE_DEFAULT_ARGS=${CMAKE_DEFAULT_ARGS}" ${ADDL_CMAKE_FLAGS}"

if [ "$(uname)" = "Darwin" ]; then
    CMAKE_DEFAULT_ARGS=${CMAKE_DEFAULT_ARGS}" -DCMAKE_CROSSCOMPILING=1 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0"
fi

echo "CMAKE_DEFAULT_ARGS: ${CMAKE_DEFAULT_ARGS}"

### build openfhe-development
OPENFHE_REPO="https://github.com/openfheorg/openfhe-development.git"
OPENFHE_DIR="${BUILD_DIR}/openfhe-development"
OPENFHE_CMAKE_ARGS=${CMAKE_DEFAULT_ARGS}
OPENFHE_CMAKE_ARGS=${OPENFHE_CMAKE_ARGS}" -DBUILD_STATIC=OFF -DBUILD_SHARED=ON"
OPENFHE_CMAKE_ARGS=${OPENFHE_CMAKE_ARGS}" -DBUILD_BENCHMARKS=OFF -DBUILD_UNITTESTS=OFF -DBUILD_EXAMPLES=OFF"
# OPENFHE_CMAKE_ARGS=${OPENFHE_CMAKE_ARGS}" -DWITH_OPENMP=OFF"

clone ${OPENFHE_REPO} ${OPENFHE_DIR}

### optionally overlay the Intel HEXL backend onto openfhe-development
if [ "${BUILD_HEXL}" = "ON" ]; then
  separator
  echo "BUILD_HEXL=ON - staging Intel HEXL overlay"
  separator

  OPENFHE_HEXL_DIR="${BUILD_DIR}/openfhe-hexl"
  clone "${OPENFHE_HEXL_REPO}" "${OPENFHE_HEXL_DIR}"

  # check out the matching tags so the overlay lands on the intended source tree
  checkout_tag "${OPENFHE_DIR}" "${OPENFHE_TAG}"
  checkout_tag "${OPENFHE_HEXL_DIR}" "${OPENFHE_HEXL_TAG}"

  overlay_hexl "${OPENFHE_HEXL_DIR}" "${OPENFHE_DIR}"

  OPENFHE_CMAKE_ARGS=${OPENFHE_CMAKE_ARGS}" -DWITH_INTEL_HEXL=ON"

  # OpenFHE bakes the imported target HEXL::hexl into the link interface of
  # OPENFHEcore/pke/binfhe in its exported OpenFHETargets.cmake, but its
  # OpenFHEConfig.cmake never re-establishes that target. So a downstream
  # find_package(OpenFHE) (openfhe-python) fails with "HEXL::hexl ... target was
  # not found". Intel HEXL does install its own config package (HEXL::hexl via
  # NAMESPACE HEXL::) into the shared install prefix, so we inject a
  # find_package(HEXL) into openfhe-python's configure, before its
  # find_package(OpenFHE) runs, via CMAKE_PROJECT_INCLUDE_BEFORE. See HEXL_INJECT
  # below where it is threaded into OPENFHE_PYTHON_CMAKE_ARGS.
  HEXL_INJECT="${BUILD_DIR}/hexl-find-inject.cmake"
  cat > "${HEXL_INJECT}" <<'EOF'
# Auto-generated by build-binaries.sh for BUILD_HEXL=ON.
# Recreate the HEXL::hexl imported target so OpenFHETargets.cmake (pulled in by
# find_package(OpenFHE)) can resolve it. CMAKE_PREFIX_PATH already points at the
# OpenFHE/HEXL install prefix.
if(NOT TARGET HEXL::hexl)
  find_package(HEXL CONFIG REQUIRED)
  message(STATUS "HEXL injected for OpenFHE: HEXL::hexl resolved via find_package(HEXL)")
endif()
EOF
fi

build_install_tag_with_args ${OPENFHE_DIR} ${OPENFHE_TAG} "${OPENFHE_CMAKE_ARGS}" ${PARALELLISM}

### build openfhe-python
OPENFHE_PYTHON_REPO="https://github.com/openfheorg/openfhe-python.git"
OPENFHE_PYTHON_DIR="${BUILD_DIR}/openfhe-python"
OPENFHE_PYTHON_CMAKE_ARGS=${CMAKE_DEFAULT_ARGS}

# For a HEXL-enabled build, make the HEXL::hexl imported target exist before
# openfhe-python's find_package(OpenFHE) includes OpenFHETargets.cmake (which
# references it). CMAKE_PROJECT_INCLUDE_BEFORE runs HEXL_INJECT right after
# openfhe-python's project() call, ahead of its find_package(OpenFHE).
if [ "${BUILD_HEXL}" = "ON" ]; then
  OPENFHE_PYTHON_CMAKE_ARGS=${OPENFHE_PYTHON_CMAKE_ARGS}" -DCMAKE_PROJECT_INCLUDE_BEFORE=${HEXL_INJECT}"
fi

clone ${OPENFHE_PYTHON_REPO} ${OPENFHE_PYTHON_DIR}
build_install_tag_with_args ${OPENFHE_PYTHON_DIR} ${OPENFHE_PYTHON_TAG} "${OPENFHE_PYTHON_CMAKE_ARGS}" ${PARALELLISM}

separator

